Repository OpenMDAO/OpenMDAO, pull requests merged in 2020-09, with the labels that each got.

#1672 Raise UserWarning each time a failure is reached in Pyoptsparse driver
  openmdao/components/meta_model_structured_comp.py
  openmdao/components/tests/test_meta_model_structured_comp.py
  openmdao/core/analysis_error.py
Labels: bug, case recording

#1699 I1629 be smarter about sparse derivatives for ExecComps with multiple expressions
  openmdao/components/exec_comp.py
  openmdao/components/tests/test_exec_comp.py
Labels: derivatives

#1698 Make auto-ivc component visible again in N2
  openmdao/recorders/tests/test_sqlite_recorder.py
  openmdao/visualization/n2_viewer/index.html
  openmdao/visualization/n2_viewer/n2_viewer.py
  openmdao/visualization/n2_viewer/src/ModelData.js
  openmdao/visualization/n2_viewer/src/N2Layout.js
  openmdao/visualization/n2_viewer/src/N2Style.js
  openmdao/visualization/n2_viewer/src/N2UserInterface.js
  openmdao/visualization/n2_viewer/src/NodeInfo.js
  openmdao/visualization/n2_viewer/style/legend.css
  openmdao/visualization/n2_viewer/tests/n2_gui_test.py
  openmdao/visualization/n2_viewer/tests/sellar_tree.json
  openmdao/visualization/n2_viewer/tests/test_viewmodeldata.py
  setup.py
Labels: n2
