Repository OpenMDAO/OpenMDAO, pull requests merged in 2022-03, with the labels that each got.

#2462 I2435 nonlinear solver recording initial data
  openmdao/docs/openmdao_book/other_useful_docs/om_command.ipynb
  openmdao/recorders/tests/test_sqlite_recorder.py
  openmdao/solvers/nonlinear/broyden.py
  openmdao/solvers/nonlinear/newton.py
Labels: bug, case recording

#2465 I2461 Added a test for solver recording when Broyden is the solver and also eliminate double recording of Broyden
  openmdao/recorders/tests/test_sqlite_recorder.py
  openmdao/solvers/nonlinear/broyden.py
  openmdao/solvers/nonlinear/tests/test_broyden.py
Labels: bug, case recording

#2468 N2 refactor: Create generic classes for ModelData, TreeNode, and others
  openmdao/visualization/n2_viewer/gen/ModelData.js
  openmdao/visualization/n2_viewer/gen/NodeConnection.js
  openmdao/visualization/n2_viewer/gen/TreeNode.js
  openmdao/visualization/n2_viewer/index.html
  openmdao/visualization/n2_viewer/n2_viewer.py
  openmdao/visualization/n2_viewer/src/ModelData.js
  openmdao/visualization/n2_viewer/src/N2Arrow.js
  openmdao/visualization/n2_viewer/src/N2Diagram.js
  openmdao/visualization/n2_viewer/src/N2Layout.js
  openmdao/visualization/n2_viewer/src/N2Matrix.js
  openmdao/visualization/n2_viewer/src/N2MatrixCell.js
  openmdao/visualization/n2_viewer/src/N2Search.js
  openmdao/visualization/n2_viewer/src/N2Style.js
  openmdao/visualization/n2_viewer/src/N2UserInterface.js
  openmdao/visualization/n2_viewer/src/NodeInfo.js
  openmdao/visualization/n2_viewer/src/OmModelData.js
  openmdao/visualization/n2_viewer/src/OmNodeConnection.js
  openmdao/visualization/n2_viewer/src/OmTreeNode.js
  openmdao/visualization/n2_viewer/src/SymbolType.js
  openmdao/visualization/n2_viewer/src/defaults.js
  openmdao/visualization/n2_viewer/src/ptN2.js
  setup.py
Labels: n2

#2448 Proposed implementation for POEM060 - reports system
  .github/workflows/openmdao_test_workflow.yml
  openmdao/api.py
  openmdao/core/driver.py
  openmdao/core/problem.py
  openmdao/core/tests/test_problem.py
  openmdao/docs/build_all_docs.sh
  openmdao/docs/ipcluster_start.sh
  openmdao/docs/openmdao_book/features/features.ipynb
  openmdao/docs/openmdao_book/features/model_visualization/main.ipynb
  openmdao/docs/openmdao_book/features/model_visualization/reports_system.ipynb
  openmdao/utils/coloring.py
  openmdao/utils/hooks.py
  openmdao/utils/reports_system.py
  openmdao/utils/tests/test_hooks.py
  openmdao/utils/tests/test_reports_system.py
  openmdao/visualization/n2_viewer/n2_viewer.py
  openmdao/visualization/scaling_viewer/scaling_report.py
  setup.py
Labels: enhancement, Awaiting POEM Acceptance, POEM

#2484 Generic versions of Diagram, Layout classes, plus update to D3 v7.3
  openmdao/visualization/n2_viewer/gen/Diagram.js
  openmdao/visualization/n2_viewer/gen/Dimensions.js
  openmdao/visualization/n2_viewer/gen/Layout.js
  openmdao/visualization/n2_viewer/gen/ModelData.js
  openmdao/visualization/n2_viewer/gen/Scale.js
  openmdao/visualization/n2_viewer/gen/TreeNode.js
  openmdao/visualization/n2_viewer/index.html
  openmdao/visualization/n2_viewer/libs/d3.js
  openmdao/visualization/n2_viewer/libs/d3.v5.min.js
  openmdao/visualization/n2_viewer/libs/d3.v7.min.js
  openmdao/visualization/n2_viewer/src/N2Diagram.js
  openmdao/visualization/n2_viewer/src/N2Matrix.js
  openmdao/visualization/n2_viewer/src/N2Search.js
  openmdao/visualization/n2_viewer/src/N2Toolbar.js
  openmdao/visualization/n2_viewer/src/N2UserInterface.js
  openmdao/visualization/n2_viewer/src/N2Window.js
  openmdao/visualization/n2_viewer/src/NodeInfo.js
  openmdao/visualization/n2_viewer/src/OmDiagram.js
  openmdao/visualization/n2_viewer/src/OmLayout.js
  openmdao/visualization/n2_viewer/src/OmTreeNode.js
  openmdao/visualization/n2_viewer/src/defaults.js
  openmdao/visualization/n2_viewer/src/ptN2.js
  setup.py
Labels: n2
