Repository OpenMDAO/OpenMDAO, pull requests merged in 2023-01, with the labels that each got.

#2696 POEM 71 Implementation
  .github/workflows/openmdao_test_workflow.yml
  openmdao/approximation_schemes/approximation_scheme.py
  openmdao/components/exec_comp.py
  openmdao/components/implicit_func_comp.py
  openmdao/components/tests/test_exec_comp.py
  openmdao/core/component.py
  openmdao/core/explicitcomponent.py
  openmdao/core/group.py
  openmdao/core/implicitcomponent.py
  openmdao/core/problem.py
  openmdao/core/system.py
  openmdao/core/tests/test_approx_derivs.py
  openmdao/core/tests/test_coloring.py
  openmdao/core/tests/test_coloring2.py
  openmdao/core/tests/test_coloring4.py
  openmdao/core/tests/test_distribcomp.py
  openmdao/core/tests/test_impl_comp.py
  openmdao/jacobians/dictionary_jacobian.py
  openmdao/jacobians/jacobian.py
  openmdao/recorders/tests/test_sqlite_recorder.py
  openmdao/solvers/linear/tests/test_petsc_ksp.py
  openmdao/test_suite/components/sellar.py
  openmdao/utils/name_maps.py
  openmdao/vectors/default_vector.py
  openmdao/vectors/tests/test_vector.py
  openmdao/vectors/vector.py
  openmdao/visualization/n2_viewer/tests/sellar_tree.json
Labels: POEM

#2742 fix bug with units check when design variable is specified in a Component
  openmdao/core/system.py
  openmdao/core/tests/test_des_vars_responses.py
Labels: bug

#2744 fix bug that caused warnings when assigning a new driver
  openmdao/utils/reports_system.py
  openmdao/utils/tests/test_reports_system.py
Labels: bug

#2746 Optimization report should now correctly compute max/min of discrete desvars.
  openmdao/drivers/tests/test_genetic_algorithm_driver.py
  openmdao/visualization/opt_report/opt_report.py
Labels: bug

#2747 Implemented POEM 079 - Warn or raise when a design variable's initial value exceed its bounds.
  openmdao/core/driver.py
  openmdao/core/tests/test_partial_color.py
  openmdao/docs/openmdao_book/_toc.yml
  openmdao/docs/openmdao_book/examples/paraboloid.ipynb
  openmdao/docs/openmdao_book/features/debugging/controlling_mpi.ipynb
  openmdao/docs/openmdao_book/features/reports/reports_system.ipynb
  openmdao/docs/openmdao_book/other_useful_docs/environment_vars.ipynb
  openmdao/drivers/differential_evolution_driver.py
  openmdao/drivers/genetic_algorithm_driver.py
  openmdao/drivers/pyoptsparse_driver.py
  openmdao/drivers/scipy_optimizer.py
  openmdao/drivers/tests/test_differential_evolution_driver.py
  openmdao/drivers/tests/test_genetic_algorithm_driver.py
  openmdao/drivers/tests/test_pyoptsparse_driver.py
  openmdao/drivers/tests/test_scipy_optimizer.py
  openmdao/recorders/tests/test_sqlite_recorder.py
  openmdao/test_suite/scripts/sellar.py
Labels: POEM

#2773 I2727 set_solver_print changes printing even in multi-run scenarios
  openmdao/core/problem.py
  openmdao/solvers/tests/test_solver_debug_print.py
Labels: enhancement

#2782 Fix bug when setting solver options, desvars, and cons with vector values
  openmdao/core/system.py
  openmdao/core/tests/test_system_set_solver_bounds_scaling_options.py
Labels: bug

#2751 POEM 75 impl branch.
  openmdao/components/exec_comp.py
  openmdao/core/component.py
  openmdao/core/explicitcomponent.py
  openmdao/core/group.py
  openmdao/core/implicitcomponent.py
  openmdao/core/problem.py
  openmdao/core/system.py
  openmdao/core/tests/test_coloring.py
  openmdao/core/tests/test_coloring2.py
  openmdao/core/tests/test_distrib_derivs.py
  openmdao/core/tests/test_distrib_derivs2.py
  openmdao/core/tests/test_mpi_coloring_bug.py
  openmdao/core/tests/test_parallel_derivatives.py
  openmdao/core/tests/test_parallel_groups.py
  openmdao/core/tests/test_theory_rev_derivs.py
  openmdao/core/total_jac.py
  openmdao/docs/openmdao_book/features/core_features/working_with_components/distributed_components.ipynb
  openmdao/docs/openmdao_book/features/core_features/working_with_groups/dist_serial.ipynb
  openmdao/docs/openmdao_book/tests/test_jupyter_output_linting.py
  openmdao/docs/openmdao_book/theory_manual/mpi.ipynb
  openmdao/jacobians/jacobian.py
  openmdao/jacobians/tests/test_jacobian.py
  openmdao/utils/array_utils.py
  openmdao/utils/assert_utils.py
  openmdao/utils/general_utils.py
Labels: docs, backwards_incompatible
