Repository OpenMDAO/OpenMDAO, pull requests merged in 2024-04, with the labels that each got.

#3184 Fixed bugs pertaining to the use of aliases in set_constraint_options and set_objective_options.
  openmdao/core/system.py
  openmdao/core/tests/test_system_set_solver_bounds_scaling_options.py
Labels: deprecation

#3185 Implementation branch for POEM93 (Linear solution caching)
  openmdao/core/problem.py
  openmdao/core/system.py
  openmdao/core/total_jac.py
  openmdao/solvers/linear/direct.py
  openmdao/solvers/linear/linear_rhs_checker.py
  openmdao/solvers/linear/petsc_ksp.py
  openmdao/solvers/linear/scipy_iter_solver.py
  openmdao/solvers/linear/tests/test_scipy_iter_solver.py
  openmdao/utils/array_utils.py
  openmdao/utils/numba.py
  openmdao/utils/relevance.py
  openmdao/utils/testing_utils.py
  openmdao/visualization/n2_viewer/tests/sellar_final_values.json
  openmdao/visualization/n2_viewer/tests/sellar_initial_values.json
  openmdao/visualization/n2_viewer/tests/sellar_no_values.json
  openmdao/visualization/n2_viewer/tests/sellar_no_values_run.json
Labels: POEM

#3202 Fix pyOptSparse `hotstart_file` `@property` method
  openmdao/drivers/pyoptsparse_driver.py
  openmdao/drivers/tests/test_pyoptsparse_driver.py
Labels: bug
